### ISSUE TITLE
Toolbar collapse /restore crashes when toolbar in vertical position

### ISSUE THREAD

**Issue by grphillips** [pubpub-zz/ppInk#112]
I have saved toolbar in vertical position (cross at top). When I try to collapse and restore using the chevron, the toolbar disappears completely.

**Comment by pubpub-zz** [comment]
This has been reported in #110, a beta version is available there. Can you confirm it is ok for you?

**Comment by grphillips** [comment]
Yes the beta version commapses and restores the toolbar OK, but it
collapses from one end and restores from the opposite end, so a lot of
mouse movement is required to collapse and restore the toolbar
sequentially. The icon it collapses to should remain in the same position
as the one that was clicked to collapse it in the first place, not six
inches lower (if using vertical orientation).

Kind regards

Geoff Phillips
gp ***@***.******@***.***

**Comment by pubpub-zz** [comment]
The dock/undock button is designed to be at the moving end whatever direction is selected since the beginning. Most of the time, if you collapse the docking it is to have screen maximized area to draw.therefore having the dock button (to collapse) nearer to the middle of the screen.
if you want to collapse/uncollapse quickly I recommend you to use the keyboard hotkey.

**Comment by grphillips** [comment]
Thanks for that. Is there any way to select where Autosave.strokes.txt  or
other preferences are stored?

Kind regards

Geoff Phillips
gp ***@***.******@***.***

**Comment by grphillips** [comment]
Also, when I close ppInk using Escape, this strange icon appears on top of
other icons on my desktop. Why?
[image: image.png]

Kind regards

Geoff Phillips
gp ***@***.******@***.***

**Comment by grphillips** [comment]
My apologies, I had inadvertantly activated a floating window (more of an
icon really).

Kind regards
Geoff Phillips
***@***.***

**Comment by pubpub-zz** [comment]
> Thanks for that. Is there any way to select where Autosave.strokes.txt or other preferences are stored?

AutoSave are stored with the images. This can yon adjusted in options (see (1) on image below)

> Also, when I close ppInk using Escape, this strange icon appears on top of other icons on my desktop. Why? [image: image.png]

_(note your capture is not visible seems to be due to use of mail input into GitHub, you may have to use web interface)_

I would guess it is the floating image ![image](https://user-images.githubusercontent.com/4083478/124348346-afe7d080-dbe9-11eb-81ec-3d2028d9dad8.png) can be used to open the toolbar in alternative to the icon in the notifications (I use it on tablets/touchscreen) if you can disable it in the options again (see (2) below. It can be also moved with right click

![image](https://user-images.githubusercontent.com/4083478/124348142-8e3a1980-dbe8-11eb-9845-deeb6d8193fc.png)

**Comment by grphillips** [comment]
Many thanks. Understood!

Kind regards
Geoff Phillips
***@***.***

**Comment by pubpub-zz** [comment]
Agree to close this issue ?

**Comment by grphillips** [comment]
Yes.

Kind regards
Geoff Phillips
***@***.***
