### ISSUE TITLE
Zoom shows wrong location/region

### ISSUE THREAD

**Issue by chuong** [pubpub-zz/ppInk#132]
Firstly many thanks for the many enhancements included in this implementation.

Zoom is one of the nice features but when I tested the latest code, it displays a zoomed-in region very far from the pointer. The expected zoomed-in region should be around the mouse position or using the mouse position as the top left corner of the zoomed regions.

**Comment by rexelbartolome** [comment]
Not entirely sure if the preview being far away from the pointer was actually intentional but regardless, I'd also like to add that because of this: trying to zoom to the edges of the screen will cause flickering on the viewfinder. 

https://user-images.githubusercontent.com/88552647/128542785-0b8a3717-a35c-4500-b0b6-cc1b1735ed03.mp4

Also the pointer is smaller and misplaced compared to what I had on screen for some reason. I used ShareX with FFmpeg to record this vid. 

I'm using a dual monitor setup if that's relevant. And also I'm really glad I found this app, I was having trouble with DemoHelper and Zoomit, so thanks for that.

**Comment by pubpub-zz** [comment]
a) on the edges, the area to be copied overlapped out of "screen" and the capture is capturing bad area. I knew this symptom but no one complained about yet. I will see if I can fix that quickly
b) ffmpeg does not capture screen cursor size and keep it at 32x32 : the bug is on its size😉 You can replace the cur files with a 32x32 and it will fix the global behavior
c) I also would recommand you to have a look at #92 discussion :  you should set the properties to ensure not trouble with mutltiple screen.

**Comment by pubpub-zz** [comment]
Can you try this version for the zoom on the borders: 
[ppInk64_Zoom07a.zip](https://github.com/pubpub-zz/ppInk/files/6949294/ppInk64_Zoom07a.zip)

About your issue with the cursor, have you tried OBS ?

**Comment by rexelbartolome** [comment]
> Can you try this version for the zoom on the borders:
> [ppInk64_Zoom07a.zip](https://github.com/pubpub-zz/ppInk/files/6949294/ppInk64_Zoom07a.zip)
> 
> About your issue with the cursor, have you tried OBS ?

Yes I usually use OBS anyway so it's no problem, I just use ShareX and ffmpeg for short video screenshots and things like that.

I've tried out the new file, and the flickering isn't present anymore, it just shows black instead, so definitely workable now in my case :D And the offset of the viewfinder to the cursor is still present, which I'm still not sure if it's intentional or not. So thanks for that 😊

**Comment by pubpub-zz** [comment]
Sorry I think I sent you to the wrong thread
Try this :
https://github.com/pubpub-zz/ppInk/issues/97#issuecomment-877617071

**Comment by rexelbartolome** [comment]
> Sorry I think I sent you to the wrong thread
> Try this :
> [#97 (comment)](https://github.com/pubpub-zz/ppInk/issues/97#issuecomment-877617071)


Yea okay, I've changed it. I don't really see a difference 😅 but I'll keep it on so I don't encounter any bugs regarding DPI and all that... Thanks 😊

**Comment by pubpub-zz** [comment]
@rexelbartolome,
Just to confirm : the problem of offset is only visible through ffmpeg and you get no offset when looking directly at the screen ?

**Comment by pubpub-zz** [comment]
@chuong,
Have you tried
[#97 (comment)](https://github.com/pubpub-zz/ppInk/issues/97#issuecomment-877617071)

**Comment by rexelbartolome** [comment]
> @rexelbartolome,
> Just to confirm : the problem of offset is only visible through ffmpeg and you get no offset when looking directly at the screen ?

Hmmmm no, either way the zoom viewfinder still has an offset from the cursor. I double-checked and I might be mistaken on my previous post as only the size of the cursor changed with using ffmpeg and I must've thought that the placement of it also changed, turns out it might be the same offset. I used OBS now for this clip and used the new version that you provided, it still has an offset but the cursor size is correct since I'm not using ffmpeg anymore :)

https://user-images.githubusercontent.com/88552647/128647993-b78f9dbd-4d1b-4891-a2d0-644b3d342bf2.mp4

**Comment by pubpub-zz** [comment]
I have some troubles to see the offset you are talking about;
When I search the  center position of the zoom it matches the head of the arrow:
![image](https://user-images.githubusercontent.com/4083478/128673180-fa017d81-7a06-4614-ad9f-5eda6c276ecb.png)

I checked quickly everywhere and it looks good. If you don't think so, can you provide the snaptshot.

**Comment by rexelbartolome** [comment]
Oh okay I understand now, the offset I was talking about was the distance between the point of the cursor and the blue box, which is highlighted in yellow
![ppInk_huUA7m74ZK](https://user-images.githubusercontent.com/88552647/128692112-e936d841-e170-4461-994c-b2427f67a74f.png)

I guess it's more noticeable when the cursor is on the lower right and the viewfinder is on the upper left. 
![ppInk_e5KX22tApV](https://user-images.githubusercontent.com/88552647/128692601-22773a93-cedf-4b9c-91e8-1a0ee3de1a59.png)


I see it as an offset because I used to use Windows' native magnifier in lens mode and the cursor is on the center of the viewfinder. I just expected the cursor to be at least inside the viewfinder, not outside of it
![ppInk_gujjQsuUYq](https://user-images.githubusercontent.com/88552647/128692583-14d95f91-983b-488d-a887-5e1457c05f5e.png)

https://user-images.githubusercontent.com/88552647/128693054-e62be3a3-0cd0-43ba-97f2-34bbcd6d26d1.mp4

But I guess that answers my question whether or not the offset was intentional or not, so maybe I just need to get used to it 😅 This way might be a better way of handling it too, since the viewfinder almost never gets clipped unlike Windows' version where if we zoom in on the corners, it gets clipped and goes outside the screen :)

**Comment by pubpub-zz** [comment]
My zoom is 100% dynamic, because of that, the enlarged area can not be displayed behind the cursor (zoomIt takes a snapshot only once and can not show changes behind.
On the pictures you have provided you can seen the zoom area is always centered on the cursor ( this is why now pixels within the rectangle centered on the cursor but out of the screens are now blackened) : the "yellow line" you've plot will never change even on borders. 😊

**Comment by pubpub-zz** [comment]
@chuong  @rexelbartolome 
I propose to close this thread

**Comment by rexelbartolome** [comment]
> @chuong @rexelbartolome
> I propose to close this thread

I'm okay with it 😄
