### ISSUE TITLE
Feature request: more selections for arrow shape

### ISSUE THREAD

**Issue by chuong** [pubpub-zz/ppInk#133]
Arrow is one of the very nice feature. Currently it works as expected but looks pretty simple. More choices for arrow shape will be wonderful. Thanks.

**Comment by pubpub-zz** [comment]
the arrow is currently a line drawn. angle and length can be adjusted. for more shapes I have to see what can be done.

**Comment by pubpub-zz** [comment]
@chuong @rexelbartolome @NOVAinc,

Here is my proposal for arrow Heads customization . the head is a bitmap scaled to match the width of the line.
to change Heads Long click on the arrow button open the dialog box(for the moment add/del are not working)
multiple press on hotkey can rotate between heads. long press on hotkey to access the dialog box is not yet coded.
There is some minor misalignment with some angles/width/heads that for me are acceptable
[ppInk64_Arrow20a.zip](https://github.com/pubpub-zz/ppInk/files/7019910/ppInk64_Arrow20a.zip)

Still a little of work but most of it is here 😊

**Comment by pubpub-zz** [comment]
@chuong @rexelbartolome @NOVAinc,
new  with a few fixes:
[ppInk64_Arrow21a.zip](https://github.com/pubpub-zz/ppInk/files/7025950/ppInk64_Arrow21a.zip)
misalignment have been fixed :  in order to cope with all ends size, you have to add a blue pixel at the horizontal position on line 101 ( middle one) where the line will be stopped.
add/del buttons are now working
REST API has been extended to select the arrow id (cf httpRequest.rtf)
Arrow ends are turned to align with the line, but if you want the end to not be rotated (ex with some square,diamond,...) the filename should start with a question mark(!)

Unless you raise issues, This release should become the Release candidate for next official release.

**Comment by pubpub-zz** [comment]
1.8RC1 released
