### ISSUE TITLE
Suggestions regarding icons

### ISSUE THREAD

**Issue by rexelbartolome** [pubpub-zz/ppInk#139]
Hello, I've made some icons that I feel like may improve visibility regarding the pens, especially when they're arranged in two lines. So I thought, once the user already made their own set of pen customizations and get accustomed to the number row hotkeys, I feel like the color is going to be the biggest priority regarding visibility, then second is what tool they're using (pen or highlighter), then lastly if it has the fading tag or not.

![image](https://user-images.githubusercontent.com/88552647/130592813-5e2035e1-33ca-4a07-bdbf-94db10426a1e.png)
![image](https://user-images.githubusercontent.com/88552647/130593732-8b334ad2-a83f-4a72-869b-e2c6253d939f.png)

So I've made the color take up the entire icon space (we can also make it more of a rounded square rather than a circle, that might be better for the active tool tag or the fading tag). The paintroller icon is just another variation (maybe if the tool has a thick width of 300+) tho we can just stick to highlighter and pen to make it more simple.

![image](https://user-images.githubusercontent.com/88552647/130593606-02002019-2b5f-4db9-9fb1-3bd04e55753e.png)

And I guess a little bonus, I made the clip art smileys look HD!

![happy](https://user-images.githubusercontent.com/88552647/130593273-a860267a-6a8b-4e6a-89d4-ddf445b8f3d6.png)
![neutral](https://user-images.githubusercontent.com/88552647/130593275-cf312ca0-54c3-4f0c-90ad-73bb6f792ee1.png)
![sad](https://user-images.githubusercontent.com/88552647/130593279-1174cc57-1a13-4793-89b8-fd9d74d6efd7.png)

They can be downloaded here :D [ppink-icons.zip](https://github.com/pubpub-zz/ppInk/files/7038172/ppink-icons.zip)

**Comment by pubpub-zz** [comment]
Thanks,
It looks nicer I agree. the image have to be split in two parts : the colored one and the rest. the gimp file is provided. I've also introduced a criteria of avg(NominalWidth,LargeWidth) to select between pen and paintroller. The highlighter is still on transparency independently of the width. 
[ppInk64_niceUI24a.zip](https://github.com/pubpub-zz/ppInk/files/7042320/ppInk64_niceUI24a.zip)

You can customize them as you wish 😊
for the image license CC-0 is preferable but CC-BY and CC-BY-SA should be good too to match MIT license. Which license would you like for your images?

Also if you want to make some test or build your own customisation, you can copy the images from src and below and modify them before saving them in ppInk folder.

**Comment by pubpub-zz** [comment]
The size of the buttons are computed from the size of the toolbar:
the current parameters are as follow
        // Button/Tooblar
        const double NormSizePercent = 0.85;   
        const double SmallSizePercent = 0.44;
        const double TopPercent = 0.06;
        const double SmallButtonNext = 0.44;
        const double InterButtonGap = NormSizePercent * .05;

I've just reviewed the size and I will certainly change them into this
        const double NormSizePercent = 0.96;
        const double SmallSizePercent = 0.47;
        const double TopPercent = 0.02;
        const double SmallButtonNext = 0.98-.47;
        const double InterButtonGap = .02;

the rendering will be as follow:
(i've added a background color on some buttons to get the actual size
![image](https://user-images.githubusercontent.com/4083478/131230598-cd35cfab-2614-428b-8caf-8c278c225f84.png)

For me Krita is no using the max size but ppInk does. there is no image padding...

**Comment by rexelbartolome** [comment]
Thanks!

I don't understand what the others meant but this is what I'm guessing:
`NormSize` refers to icons that take up the whole toolbar, so Pointer, Snapshot, Redo, Delete right?
`SmallSize` refers to small icons like the Pen 0- 9, Handfree, Line, Rectangle, and Ellipse;
`TopPercent` I think refers to the gap between the top edge of the toolbar and the icon
`InterButtonGap` refers to the gap between the small top button and the small bottom button

I'm not sure what `SmallButtonNext` means and it's kind of confusing why it has two values in the one that you sent 😅

>For me Krita is no using the max size but ppInk does. there is no image padding...

Are you just saying that Krita doesn't have padding or are you also saying that you weren't able to find a good way to add padding to the image icons? :(
If you happen to not find a way, I can always do the padding inside Adobe Illustrator... Might not be the best way but it can get the job done I guess. Fortunately, it's non destructive, so I can export the icons with padding and without padding.

Are there also any news regarding anti-aliasing issues? 😮 For these icons, I went with 64x64 so it doesn't have a hard time scaling down to 28px or 32px. I think bigger icons (like 128x128) have a bigger tendency to have aliasing issues. But this also means making the toolbar bigger would make it look a little blurry than before...

Some notes when I tested the build in this Issue Thread:

- pinned.png and unpinned.png aren't updating. 
- I don't personally use the video recording aspect of ppInk so just let me know if the icons match the meaning that you intended.
- A bolder and thiccer logo! Hope you like it 😊 I made the system tray icon the proper size too, so it doesn't have anti aliasing issues.
- Floatingcall.png have aliasing issues(?), it has a white outline around the image
- Outside/Empty versions of the tools use the scissors icon, so it might make more sense to name the tool Cutout instead of Outside/Empty 

**[NiceUI_icons.zip](https://github.com/pubpub-zz/ppInk/files/7071654/NiceUI_icons.zip)**

Here's what they look like right now, I can also change the color easily, so we might be able to do a ppInk Dark Mode version if we really want to 😄
![image](https://user-images.githubusercontent.com/88552647/131233349-6a1697c2-aaa3-4005-9d04-715d05d2f572.png)
![image](https://user-images.githubusercontent.com/88552647/131233469-12862564-8a3b-48c7-a40a-1d887d791748.png)

**Comment by pubpub-zz** [comment]
@rexelbartolome 
Thanks for you great job. It is very nice!

> I don't understand what the others meant but this is what I'm guessing:
> `NormSize` refers to icons that take up the whole toolbar, so Pointer, Snapshot, Redo, Delete right?

correct

> `SmallSize` refers to small icons like the Pen 0- 9, Handfree, Line, Rectangle, and Ellipse;

correct

> `TopPercent` I think refers to the gap between the top edge of the toolbar and the icon

still right

> `InterButtonGap` refers to the gap between the small top button and the small bottom button

No, it is the horizontal space between 2 buttons (small or big)
 
> I'm not sure what `SmallButtonNext` means and it's kind of confusing why it has two values in the one that you sent 😅
it it the vertical position for the bottom small  buttons
 
> > For me Krita is no using the max size but ppInk does. there is no image padding...
> > Are you just saying that Krita doesn't have padding or are you also saying that you weren't able to find a good way to add padding to the image icons? :(

no it is the opposite : Krita has some padding that is not in ppInk, If you want to add padding, it has to be within the png currently

> If you happen to not find a way, I can always do the padding inside Adobe Illustrator... Might not be the best way but it can get the job done I guess. Fortunately, it's non destructive, so I can export the icons with padding and without padding.

Due to the button size in order to get maximum readability I would prefer to not add padding,

> Are there also any news regarding anti-aliasing issues? 😮 For these icons, I went with 64x64 so it doesn't have a hard time scaling down to 28px or 32px. I think bigger icons (like 128x128) have a bigger tendency to have aliasing issues. But this also means making the toolbar bigger would make it look a little blurry than before...

Your observation looks pertinent and your set of icons being 64x64 seems pertinent. The blurry seems for me acceptable.

> Some notes when I tested the build in this Issue Thread:
> 
>     * pinned.png and unpinned.png aren't updating.
fixed
> 
>     * I don't personally use the video recording aspect of ppInk so just let me know if the icons match the meaning that you intended.

   Good for me

>     * A bolder and thiccer logo! Hope you like it 😊 I made the system tray icon the proper size too, so it doesn't have anti aliasing issues.

It looks great!
 
>     * Floatingcall.png have aliasing issues(?), it has a white outline around the image

due to limitation in c#/windows, background images can deal with transparent color but not alpha : this is why you are getting the whitening when color is including alpha.
![FloatingCall](https://user-images.githubusercontent.com/4083478/131408613-b3b9d454-3002-4880-8f14-6dd5553c4e6b.png)

PS : can you provide me with the icon_red.ico (which is blue ... 🤣) in xcf format.

>     * Outside/Empty versions of the tools use the scissors icon, so it might make more sense to name the tool Cutout instead of Outside/Empty

for me just scissors and the dashed line is not clear I would prefer to add filling out:
![tool_oval_out](https://user-images.githubusercontent.com/4083478/131408039-462bc495-000d-4d8c-a8e6-11e43cc9abaa.png) ![tool_hand_out](https://user-images.githubusercontent.com/4083478/131408042-08a3a616-3b3c-4e2f-b69e-fca732bfa565.png) ![tool_rect_out](https://user-images.githubusercontent.com/4083478/131408043-f0a0a296-e382-4d90-aeb7-fb6ce4c3748e.png) ![tool_mlines_out](https://user-images.githubusercontent.com/4083478/131408045-00f4ca70-294d-44b5-a929-9d432c635e11.png)

> 
> Here's what they look like right now, I can also change the color easily, so we might be able to do a ppInk Dark Mode version if we really want to 😄

If you can propose a dark theme It would be great : I agree with you, it will be certainly appreciated.

Based on your proposal I would propose a few more adjustments:
Color Picker : I've added an icon
![tool_picker](https://user-images.githubusercontent.com/4083478/131408463-88cbeab1-6240-4369-808a-855f86d2019a.png)

Polyline : I think it would be clearer with an open line:
![tool_mlines](https://user-images.githubusercontent.com/4083478/131408580-f5b57200-ba92-488a-a2f1-d18d7100279a.png)

**Comment by pubpub-zz** [comment]
+ latest build
[ppInk64_newUI30b.zip](https://github.com/pubpub-zz/ppInk/files/7080051/ppInk64_newUI30b.zip)

**Comment by rexelbartolome** [comment]
I'll reply to the other stuff you said in a later post and do the changes you proposed with the filling out, polyline and the color picker! 😊 But I can't export to xcf unfortunately, I can export to SVG though? Which Gimp can read as far as I know. I included the white, blue, and black.
[icons.zip](https://github.com/pubpub-zz/ppInk/files/7093773/icons.zip)

I feel like padding is essential, how do you feel about the icons right now? I've made them 75% smaller so it has space around it. We can make it bigger like 80% but I feel like 85% is the most that we can do if you want to make them bigger.

**Comment by pubpub-zz** [comment]
@rexelbartolome  
> I'll reply to the other stuff you said in a later post and do the changes you proposed with the filling out, polyline and the color picker! 😊 But I can't export to xcf unfortunately, I can export to SVG though? Which Gimp can read as far as I know. I included the white, blue, and black.

Perfect !
 
> I feel like padding is essential, how do you feel about the icons right now? I've made them 75% smaller so it has space around it. We can make it bigger like 80% but I feel like 85% is the most that we can do if you want to make them bigger.

Can you show me the different proposition

**Comment by rexelbartolome** [comment]
75% scale
![image](https://user-images.githubusercontent.com/88552647/132103914-c5b6e137-4e52-42a8-bbde-c8567553044f.png)

80% scale
![ppInk_3MdZIEWGp7](https://user-images.githubusercontent.com/88552647/132104060-db57b7f4-9a2e-4403-a08d-6153b16c4214.png)

85% scale
![ppInk_iuPOseBTYL](https://user-images.githubusercontent.com/88552647/132104067-5f29d507-cfd5-4e83-abe9-85a69131f2d3.png)

I'm leaning more towards 75% or 80% in my honest opinion, 85% is starting look a bit cramped.

https://user-images.githubusercontent.com/88552647/132104523-6d53d194-57b4-4059-a20f-809dd15f259a.mp4


The eyedropper I've experimented with a different design, so it looks similar to the eraser cursor so just let me know what you think, we can still do the black outline thing on the left if you want.
![image](https://user-images.githubusercontent.com/88552647/132104122-49126475-a83f-40ef-b3f2-488397716e9a.png)

Also, changing the cursorarrow.png results in making it smaller than it used to be.
![image](https://user-images.githubusercontent.com/88552647/132104480-d8afce94-1a34-48ee-a6e2-f3e1de0b87e8.png)

Testing it out cause I want to see what it would look like if the cursor had a white outline of some sort to improve visibility across all types of screens instead of just red.

![image](https://user-images.githubusercontent.com/88552647/132104519-89097f02-e61d-4891-b53c-307d4f7556c2.png)

**Comment by pubpub-zz** [comment]
> 75% scale
> 80% scale
> 85% scale
> 
> I'm leaning more towards 75% or 80% in my honest opinion, 85% is starting look a bit cramped.

None is shocking for me, for me the biggest the icons are, the nicer it looks. so 80% as a trade-off 

> The eyedropper I've experimented with a different design, so it looks similar to the eraser cursor so just let me know what you think, we can still do the black outline thing on the left if you want.

There is now 2 images now the icon one:
a) the icon one:
![tool_picker](https://user-images.githubusercontent.com/4083478/132207720-24184331-df64-430c-968c-0ae4144a255d.png)

b) the cursor
![picker](https://user-images.githubusercontent.com/4083478/132207926-ec6ef5ef-f8b0-4b7b-ade9-befaf170643b.png)

The cursor one is modified based on the color picked up : this one should be only white and back. ok for your proposal for the icon one.


> Also, changing the cursorarrow.png results in making it smaller than it used to be.

in order to get big cursors, they should be ico with only one image in: the image, is applied and the designation is defined in the middle of the image : this is why the red arrow is only drawn on the lower right corner.

> Testing it out cause I want to see what it would look like if the cursor had a white outline of some sort to improve visibility across all types of screens instead of just red.

Personnally, I think that a white will not ease to identify the border and therefore the designation pixel. If you want to add one, you should not get over 1pixel wide.

**Comment by rexelbartolome** [comment]
Ohhh I like the modifiable color on the color picker! Good design decision :)

I've now made all the icons at 80% ! 🥳

>Personnally, I think that a white will not ease to identify the border and therefore the designation pixel. If you want to add one, you should not get over 1pixel wide.

I see, then how do you feel about the color of the default cursor then? I can make it yellow too so that everything has the same color, but you can leave it as it is. 

I think I'll have a white one with thick black outlines, but I'll just change it by uploading my own ico. I'll add it to the zip for options I guess. I've also changed some minor stuff, like the magnet, the shape_outside, cursoreraser.ico and unpinned icons.
[icons_NiceUI80.zip](https://github.com/pubpub-zz/ppInk/files/7155117/icons_NiceUI80.zip)

**Comment by MikeTheGreat** [comment]
Hello!

First - the revised icons & visual design looks awesome!

While the visual design is being revised - would it be possible to put a solid color behind the icon in the Windows System tray?
(Putting the same color behind the icon in the task bar would be great too!)

I've got a non-standard background color for Windows (green) and the icon is almost invisible.  Other icons (like Zoom or Steam) put a background behind the icon so it's clearly visible no matter what the background color is.

Here's an example of the system tray:
![image](https://user-images.githubusercontent.com/551619/136982405-6f8170a3-0117-4137-89af-69a6723a08cf.png)

The task bar:
![image](https://user-images.githubusercontent.com/551619/136998645-2cee6bea-f138-4331-828f-ddc4e3b307d2.png)

(The task bar is easier to see because the icon is bigger, but it still doesn't stand out well).
