### ISSUE TITLE
No Toolbar?

### ISSUE THREAD

**Issue by lin-ycv** [pubpub-zz/ppInk#149]
As seen in the video, I don't have a toolbar, only a floating icon that cannot be moved.
https://user-images.githubusercontent.com/60565737/134915239-6f238390-8132-46d3-901b-88bab04ba83f.mp4

Also, there's a slight lag when enabling drawing.
When drawing long lines, they jitter slightly.

**Comment by pubpub-zz** [comment]
Hi @lin-ycv ,
As said on https://github.com/pubpub-zz/ppInk ,The floating window can be moved using the right click. About the toolbar not appearing, I would guess that it is 'displayed' on an area of screen(s) display because your toolbar. You may recover it if you unset the allow dragging :
![image](https://user-images.githubusercontent.com/4083478/134952354-03fafd61-4be6-44f9-92d1-b4a0265c0336.png)
When opening the toolbar, it will be "stuck: to a screen border. once redisplayed, you can set back the option to move it whereever you want.

**Comment by lin-ycv** [comment]
I think there's come compatibility issues with multi display setup?
If I only display to one monitor, it works fine.
But if I use extended display, I'll see the FloatingCall icon, but when i click it, tool bar does not appear, even after toggling Allow dragging toolbar option on and off

**Comment by lin-ycv** [comment]
Fixed by setting High DPI scaling override to Application in Compatibility

**Comment by pubpub-zz** [comment]
@lin-ycv
happy it is fixed. Do not hesitate to star it if you like it 😊
