### ISSUE TITLE
Grandient color support?

### ISSUE THREAD

**Issue by aluferraz** [pubpub-zz/ppInk#179]
Hi there!

Congrats for this program, it's unbelievably awesome!!  It would be nice to have a gradient option on pen color selection, something like this:

![image](https://user-images.githubusercontent.com/5156410/154817256-05f1c4dd-5c2a-4e0c-ad68-0e1274d76a71.png)

Maybe have an animated gradient, where the line colors flows into the gradient colors...

Any thoughts on that?

**Comment by pubpub-zz** [comment]
Hi @aluferraz,
ppInk relies mainly on strokes from microsoft Ink library. This class does not offer gradient colors. also the  implementation of multiple colors will increase the complexity of the UI.
In order to provide such an effect, I would recommend you to use cliparts that could predefine some prefined shapes with gradients that can be then be animated.

**Comment by aluferraz** [comment]
Hello!

Thank you so much for replying! That's a perfect solution, I'll definitely try it out!! 😁
😁
