### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by leo6686** [pubpub-zz/ppInk#182]
[crash.txt](https://github.com/pubpub-zz/ppInk/files/8309219/crash.txt)
[config.ini.txt](https://github.com/pubpub-zz/ppInk/files/8309221/config.ini.txt)
[hotkeys.ini.txt](https://github.com/pubpub-zz/ppInk/files/8309222/hotkeys.ini.txt)
[pens.ini.txt](https://github.com/pubpub-zz/ppInk/files/8309223/pens.ini.txt)
@pubpub-zz

**Comment by pubpub-zz** [comment]
Hi @leo6686,
Thanks for the report
Some fixes have been implemented since. Can you try to with the latest beta version
[ppInk64_RestWidth06a.zip](https://github.com/pubpub-zz/ppInk/files/8193038/ppInk64_RestWidth06a.zip)

Can you also tell me if you found a scenario which is then creating the crash.

**Comment by leo6686** [comment]
您好，您发给我的邮件已经收到，谢谢。
------------姚

**Comment by pubpub-zz** [comment]
@leo6686,
any update ? (in english please)

**Comment by leo6686** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月28日(星期一) 凌晨3:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pubpub-zz/ppInk] crash (Issue #182)





 
@leo6686,
 any update ? (in english please)

**Comment by pubpub-zz** [comment]
@leo6686 
your message is unreadable
