### ISSUE TITLE
Snapshot on close

### ISSUE THREAD

**Issue by CfKu** [pubpub-zz/ppInk#202]
Hi,

It would be nice to have a new option: If enabled, ppInk would create a snapshot of whole screen (also in dual monitor setup) to default save path after closing the toolbar. 

Regards
CfK

**Comment by pubpub-zz** [comment]
to get a snapshot, you just need to click on the snapshot button and just do one click which is not so complex.
your request is very specific and does not match a general need.
If your issue is that you forget to do your snapshot before exiting, you current strokes are stored and can be restored with a short click on the load button (at the very end on right) : you can then readjust.
if you are really looking for the feature, feel free to propose a PR with adequate capability to enable/disable it

**Comment by CfKu** [comment]
The later. Thanks for that hint.

**Comment by pubpub-zz** [comment]
no update : the issue is too old
