### ISSUE TITLE
Clipart Function (NEW) - Allows user to add custom icons (such as smileys, etc)

### ISSUE THREAD

**Issue by JamesZing** [pubpub-zz/ppInk#46]
For the Clipart function (newly added handwriting tools), it would be more intuitive to simply left-click to add each clipart; much like the Numbered Chip (N) function. 

*If a user would like to change its default size, he/she may set their preferred size in Options. 

**This improvement could also be applied to the existing Numbered Chip (N) function, where the size is already pre-fixed but not yet customizable by the user.

**Comment by pubpub-zz** [comment]
short click do paste the symbol
The preferred size of a clipart is defined by the original image size : you can resize easily any cliparts that way and get different sizes for the different images

The size of the number chip can be currently defined by the default font setup. The default font can be modified in the options dialog box, and it can be modified for the time of a drawing session through a long click on edit button

**Comment by pubpub-zz** [comment]
tag size/font added independently from text size/font
beta release availabe in issue #47

**Comment by JamesZing** [comment]
Short-clicking does add the symbol with a pre-fixed size, kudos!

**Comment by pubpub-zz** [comment]
Can you give me feedbacks on your tests : are you getting the stamps with the latest version?
[ppInkShrtCut2.zip](https://github.com/pubpub-zz/ppInk/files/6025238/ppInkShrtCut2.zip)

**Comment by pubpub-zz** [comment]
@JamesZing,
can you give me status of your issues / tests ?

**Comment by eamayreh** [comment]
Since this thread is relevant to what I have in mind, here's my question. How do you properly use the "from clipboard" feature in the clipart?
![from_clipboard](https://user-images.githubusercontent.com/61389799/110765903-4ff5a480-825d-11eb-8314-ca251d06cdd6.png)

I tried copying other images to clipboard from snagit but couldn't paste it to PPink drawing canvas; I keep getting this error as soon as I click on "From Clipboard" button:
![from_clipboard_error](https://user-images.githubusercontent.com/61389799/110766662-15403c00-825e-11eb-9436-97181d39c0be.png)

When I copy (images, icons, drawings) from this website,  [https://coolsymbol.com/](url), I don't get any errors; but this time there is nothing pasted or drawn on the screen. 

What am I doing wrong? I'll try to upload a video later today demonstrating both instances.

**Comment by pubpub-zz** [comment]
Hi @JamesZing,
Without feed backs  I will close this issue for issue tracking clarification. Do not hesitate to reopen it when you will have new information.
