### ISSUE TITLE
New shortcut - Toggle through enabled pens

### ISSUE THREAD

**Issue by JimMiskelly** [pubpub-zz/ppInk#49]
A single key shortcut to toggle through pens shown on toolbar would be most helpful.

**Comment by pubpub-zz** [comment]
I do not see how to use such a shortcut and its implementation will be tricky with the different tools,
I will leave it opened and tagged it to ask other users opinion : 
Message to all, can you please give your opinion and describe usecase

**Comment by JimMiskelly** [comment]
I only need 4 colors max for marking up so I reduced my pen pallet. I use a graphics tablet with a limited number of buttons and can't afford to assign each pen a button. If there was a shortcut key to cycle through the pens, I could map it to one button and be able to select any pen (color) with a few taps. Happy days!
![Reduced pen selection](https://user-images.githubusercontent.com/43499067/106074367-a4a4ec00-6103-11eb-9f24-315e547fd222.png)

**Comment by pubpub-zz** [comment]
I've finally found a way to implement one shortcut to rotate through pens without impacting the standard behavior
[ppInk rotate Pens.zip](https://github.com/pubpub-zz/ppInk/files/5889233/ppInk.rotate.Pens.zip)

in order to activate the function you have to put the same shortcut in pen 0 and pen 1:
![image](https://user-images.githubusercontent.com/4083478/106180488-a53d9100-619c-11eb-8f04-acb63bb0b109.png)

**Comment by JimMiskelly** [comment]
Great. Thanks for adding the function. It works well.
