### ISSUE TITLE
Whiteboard

### ISSUE THREAD

**Issue by niekine** [pubpub-zz/ppInk#58]
@pubpub-zz can you add button to activate white blank screen for note taking.

**Comment by pubpub-zz** [comment]
White blank screen is already available through long click on the clear button(bin)

**Comment by niekine** [comment]
@pubpub-zz i will try it it, but i mean completely white blank screen.

**Comment by niekine** [comment]
@pubpub-zz I'm sorry, i could not see. But i want to switched to white screen on second display. When i switched to blank there is only change on first display. How can i change from first to second display.

**Comment by pubpub-zz** [comment]
actually this is a bug. thanks for the indication 😊.
[ppInkBeta.zip](https://github.com/pubpub-zz/ppInk/files/5998653/ppInkBeta.zip)

actually the whiteboard applies to the whole area. If you want just one screen, just draw a white rectangle on the screen you want to whiten

**Comment by pubpub-zz** [comment]
is it ok now for you?

**Comment by chrisj0192** [comment]
it would be interesting if the whiteboard or blackboard could opened by hotkeys. Because I manage the program with full hotkeys.
Another issue I've noticed is when I combine alt + a key, for examaple 'alt + a'  to use the arrow, if I press 'alt + a (two times)' the arrow gets stuck and I need to press a key with the handfree drawing to use again. I'm not sure if that issue is a bug, but when I draw rectangles, ovals and lines, it doesn't happen.

**Comment by chrisj0192** [comment]
it would be interesting if the whiteboard or blackboard could opened by hotkeys. Because I manage the program with full hotkeys.
Another issue I've noticed is when I combine alt + a key, for examaple 'alt + a'  to use the arrow, if I press 'alt + a (two times)' the arrow gets stuck and I need to press a key with the handfree drawing to use again. I'm not sure if that issue is a bug, but when I draw rectangles, ovals and lines, it doesn't happen.

**Comment by chrisj0192** [comment]
it would be interesting if the whiteboard or blackboard could opened by hotkeys. Because I manage the program with full hotkeys.
Another issue I've noticed is when I combine alt + a key, for examaple 'alt + a'  to use the arrow, if I press 'alt + a (two times)' the arrow gets stuck and I need to press a key with the handfree drawing to use again. I'm not sure if that issue is a bug, but when I draw rectangles, ovals and lines, it doesn't happen. I'd like to learn about how to program because I want to contribute with your  fantastic program. I really like it.

**Comment by pubpub-zz** [comment]
I did not though originally that this tool would be access often as once configured though the long click, the real action is engaged through the short click : I've coded the access through the alt+ (do not forget to activate the hot key for the clean tool)
About alt+arrow, thanks, it is a bug normally fix can you check for side effects.
[ppInk28.zip](https://github.com/pubpub-zz/ppInk/files/6056949/ppInk28.zip)

Happy you're enjoying the program. do not hesitate to star it 😉. I'm open to contribution that are extending of fixing the program : if you want to start you should have a look in FormCollection that contains most of the behavior and do not hesitate to ask questions.

**Comment by pubpub-zz** [comment]
@chrisj0192 
Can you provide status on your tests and eventually close this issue

**Comment by chrisj0192** [comment]
Hello friend, as I told you in another post I apologize for not having answered your comment before. About the whiteboard and blackboard everything is ok :D, the new function is perfect!, btw, Do you think I could configure that funciton with a custom hotkey?, thanks in advance my friend!

**Comment by pubpub-zz** [comment]
As said Alt + (clear shortcut) will engage selection of the background. after first background selection, the clear button / shortcut will apply the previously selection background
note also that the background is 'just' a rectangle covering the whole area.

**Comment by pubpub-zz** [comment]
@chrisj0192 
Can we close this issue ?

**Comment by chrisj0192** [comment]
Hello friend, yes you can close this issue, i'd like to close this issue but I'm not the owner. btw thanks a lot for your help.
