### ISSUE TITLE
Zoom in multiple monitor setup

### ISSUE THREAD

**Issue by lucacuccu3x8** [pubpub-zz/ppInk#70]
Hi pubpub
Please, notice the behaviour of the zooming when against a multiple monitor set-up.
It's not an issue to me in particular, but maybe something that could bug someone else?
Please, see video

https://user-images.githubusercontent.com/9900115/111182437-d20c0300-85a6-11eb-89f8-88ef92411131.mp4

**Comment by pubpub-zz** [comment]
can you please clarify what is odd from your point of view

**Comment by lucacuccu3x8** [comment]
You didn't notice the different behaviour of the zooming window?
in screen 1 all good as default
in screen 2 it moves top right - far from the mouse pointer
in screen 3 it moves top left - very far from mouse pointer

![Screenshot 2021-03-16 211955](https://user-images.githubusercontent.com/9900115/111381477-ac155a00-869d-11eb-80ca-c8fa006aa331.jpg)
![Screenshot 2021-03-16 212505](https://user-images.githubusercontent.com/9900115/111381816-1af2b300-869e-11eb-81c5-0cac4af34ee7.jpg)
![Screenshot 2021-03-16 212406](https://user-images.githubusercontent.com/9900115/111381818-1b8b4980-869e-11eb-8404-d5ab92649e2a.jpg)
![Screenshot 2021-03-16 212315](https://user-images.githubusercontent.com/9900115/111381819-1b8b4980-869e-11eb-9eaa-070e6f59fbcc.jpg)

**Comment by pubpub-zz** [comment]
The zoom window take a box centered on the cursor hot point (the arrow head inhere) and enlarge it in a window next very next to it.(actually the two corners touches each other:
![image](https://user-images.githubusercontent.com/4083478/111386308-5b592d80-86ac-11eb-9b4a-3dba8a7b0e10.png)
in this example I've surrounded the area with a blue rectangle.
When the enlarge window can not be displayed because to near from the border of the screen, the window is sent higher or on left to display. When you are sending the mouse to screen 2, during a very short time, the mouse is not far away from the bottom of screen, the window can not be displayed and is therefore sent on the top right of the cursor. It stays there until the window was no nore displayable. If you had had move the screen next to top of screen 2, it would have move back down.

You can check on your captures that the original area wich is zoomed reaches the nearest corner of the enlarged image
