### ISSUE TITLE
希望它是这个样子，并且可以在边界隐藏。

### ISSUE THREAD

**Issue by tourxp** [pubpub-zz/ppInk#85]
![无标题](https://user-images.githubusercontent.com/66894546/116870504-4416d500-ac45-11eb-8bd3-d0980c4adfe5.png)
感谢您增加了这些功能。
我希望它是这个样子，并且可以在边界隐藏，供您参考。
谢谢。

**Comment by pubpub-zz** [comment]
can you please translate in english

**Comment by pubpub-zz** [comment]
using Google Translate, after some attemps, I've understood that you were trying to set the toolbar like your drawing. the orignal capabilities to customize the toolbar are limited. What I can propose you is the capability to set the pens on two lines(Beta version attached) In order to set the buttons as you are proposing, you just have to modify the buttons templates and put them in ppInk folder.
[ppInk64_15a.zip](https://github.com/pubpub-zz/ppInk/files/6488172/ppInk64_15a.zip)

Give me your feedbacks

**Comment by pubpub-zz** [comment]
without feed back I close this issue. feel free to reopen it if you have new inputs
