### ISSUE TITLE
Dashed Lines

### ISSUE THREAD

**Issue by pubpub-zz** [pubpub-zz/ppInk#98]
> Dashed lines:
> Including a dashed line would be quite useful when we need to draw a solid shape, for example when we want to represent lines that are on the back of a prism.

I agree this could be interesting, but Not sure how to handle that with strokes (do not know if strokes drawing can be done with that. Will think about it. 👍

_Originally posted by @pubpub-zz in https://github.com/pubpub-zz/ppInk/issues/95#issuecomment-844534760_

**Comment by pubpub-zz** [comment]
Alpha version of dash (still partial)
[ppInk64_dash1.zip](https://github.com/pubpub-zz/ppInk/files/6556056/ppInk64_dash1.zip)
@NovaInc, can you test it. DashStyle is currently available only when in the Pen Edit DialogBox. Can you tell me if it is working for you and also, if the Variable width (with the pen pressure) is still working correctly (both in drawing and in stroke only capture).
I'm sorry the pen pressure will not work with dashstyle.

**Comment by NOVAinc** [comment]
![2021-05-27 20-19-21](https://user-images.githubusercontent.com/19545604/119908390-d77fb500-bf28-11eb-85f1-70c34295c73e.png)
This is my test with smooth curves off. When I went to drag the box for the snapshot, a dashed stroke followed the cursor and can be seen on top of the other strokes. I used the highlighter because the stroke is wider and artifacts are easier to see

Here is the test with smooth curves on
![2021-05-27 20-24-26](https://user-images.githubusercontent.com/19545604/119908686-8cb26d00-bf29-11eb-9dd3-ec421d216b23.png)

With smooth curves off, it seems to glitch out a lot. From my testing, using dashed strokes with pen while having smooth curves off resulted in increased artifacts with more pen pressure, but it was pretty glitchy overall so it's hard to tell. With smooth curves on, it doesn't seem to glitch out as much with either input method, and I'd say it's quite usable.

**Comment by NOVAinc** [comment]
I forgot to report that when I tried to save the strokes, so I could switch smooth curves off and then load the original strokes again, they get loaded back as simple strokes with none of the styling.

I provided 2 separate snapshots because if you have cursor mode and you right click on ppink's icon in the task bar, you can't click options because the toolbar expands with right click too. You can still click exit with the toolbar extended and the program closes, but options aren't accessible.

**Comment by pubpub-zz** [comment]
As said the version was a very first release. This is now fixed, also Options are extended, Hotkey and REST API completed.I think now it can be considered completed.
[ppInk64_Dash2.zip](https://github.com/pubpub-zz/ppInk/files/6563440/ppInk64_Dash2.zip)

@chrisj0192 if you want also to have a try also

**Comment by eamayreh** [comment]
@pubpub-zz hmm, was trying this and as soon as I run it I got these error messages:

![image](https://user-images.githubusercontent.com/61389799/120050096-d6cc4900-c024-11eb-85f1-0d81139e01b3.png)
and when choosing "no" in that dialog box, I get this:
![image](https://user-images.githubusercontent.com/61389799/120050131-ec417300-c024-11eb-9b8b-4a1b638e827a.png)

Here's the crash log file it created afterwards:
[crash.txt](https://github.com/pubpub-zz/ppInk/files/6563674/crash.txt)

**Comment by eamayreh** [comment]
> @pubpub-zz hmm, was trying this and as soon as I ran it I got these error messages:

Nvm, it seems I just had the .exe somehow cut to my desktop without the other PPink files, lol. It's working fine.

**Comment by NOVAinc** [comment]
![2021-05-28 21-35-10](https://user-images.githubusercontent.com/19545604/120052854-c3f24e00-bffd-11eb-81af-c881ab729f01.png)
![2021-05-28 21-40-53](https://user-images.githubusercontent.com/19545604/120052856-c654a800-bffd-11eb-9a32-48ce581a7790.png)

These are the tests for version 2.

When I had smooth on and I went to take the screenshot, after finishing drawing the snapshot box the edit text window popped up and I immediately got an error after that, then it crashed. With smooth off I had the same unintended stroke bug appear again when trying to draw the snapshot box from the top left corner.

This is not related to the stroke styles, but I think also having pens in the toolbar in 1-2-3-4-5 on the first line and then 6-7-8-9-10 on the second line would be more intuitive than 1-3-5-7-9, 2-4-6-8-10, since that's the way we read. Top left to top right then skip to the next line.

**Comment by chrisj0192** [comment]
Hello friend! Wow, I was trying your release and let me tell you that I never imagined that you would implement dashed lines for strokes 😲. To be honest my idea was another one with dashed lines hehe. But you are amazing.
Well I was doing a lot of tests and this is my report:
The implementation is generally Ok , it seems that I found a little bug but I'm not sure, I did many  tests to confirm it.  On the other hand I was testing dashed lines with strokes and shapes (arrows, ovals, rectangles, lines, Every time you implement a new function in ppink I'm quite curious how well it works hehe, that's the reason why I do a lot of tests and I enjoy doing that.

My report about dashed line function (bugs and usability):
As I told you in another issue, I like using pplink with hotkeys and preferably with the "ALT key" combining it with other keys.
So, I started drawing some solid lines by using "line" option.
For example, in my case I make a line with "alt + w" (because when I release "alt" key the pen returns automatically to be used). this function makes ppink really dynamic and further easy to do a lot of things whatever you want to do.

Now, Regarding  dashed lines I cannot do that :(, I was trying to do something similar but it's  a little bit hard to do it
For example: When I press "alt + w" to do a line, I release "w" key  and then I just press "a" key to start making an arrow (without releasing "ALT").
Another example is when I change line /polyline/ colored polygon depending on how many times I press "w" ( in my case) previosly pressing "alt".

I was trying to combine "line" with "dashed line" and was trying to find an easy way to do it dynamically by setting "alt + d" for the dashed lines. But the dashed line doesn't reset when I release "alt" using it.

Another one that I've noticed is that when I deactivate ppink and activate it again, dashed lines don't start with the principal solid line.
I think the principal line (green) is the most useful in this case. and the other types of lines could be secondary lines.

a short example what I would like to do with less effort.
https://user-images.githubusercontent.com/20199672/120055616-df108e00-bffc-11eb-80fc-82f9eb39e678.mp4

Testing dashed lines with "the smooth curve option" disabled.
https://user-images.githubusercontent.com/20199672/120055646-05362e00-bffd-11eb-8abc-7c22bb69ade9.mp4

Testing other shapes and the hightlighter with dashed lines.
https://user-images.githubusercontent.com/20199672/120055667-21d26600-bffd-11eb-8b19-c1b1bc2108bb.mp4

That's all I can tell you. I don't know if you might want to consider what I told you above to make this process more dynamic. I'd love to do a great change lines with dashed lines in a fast way with "alt" key. 

For me it is enough if I can make a dashed arrow or a dashed line with an option similar to lines, arrows, rectangles and ovals regardless of the strokes because I know that strokes are more difficult.

I know that you have great ideas friend and you'll improve it! . I hope this report can you improve much more your amazing software.

Thanks in advance and as I told you I'm willing to help you with tests and translation. I will take more free time to do more reports in order to contribute with you.

**Comment by chrisj0192** [comment]
I'm attaching some extra videos that I made when I was testing dashed lines. In my opinion I think it's not so relevant dashed lines with the pen but you might want to improve it. That's why I'm sharing this results with you.

Testing dashed lines with the pen.
https://user-images.githubusercontent.com/20199672/120061108-2f99e280-c021-11eb-93c7-13143dcf758f.mp4

Testing rectangles and ovals.
- I've noticed some irregularities.
https://user-images.githubusercontent.com/20199672/120061120-4809fd00-c021-11eb-8c4a-c526219bc099.mp4

Testing arrows.
- In this case it would be pretty interesting when me van to make a dashed arrow keeping the arrowhead. I've notice irregularities too and when the line is fine the arrowhead is asymmetric.
https://user-images.githubusercontent.com/20199672/120061197-b3ec6580-c021-11eb-8a80-903d6c6bfc50.mp4

Testing lines (This is what I really wanted to tell you with the idea of the dashed lines)
There are two types of dashed lines that I really like. I highlighted them in the video. It's perfect for me.
https://user-images.githubusercontent.com/20199672/120061254-fc0b8800-c021-11eb-9d72-a6b0af3416eb.mp4

As I told you before, I know that drawing dashed lines with strokes is a big challenge. So for me it's enough if you consider what I told you in my previous post (considering hotkeys and "alt" key to use them in a fast way similar to a line/polyline/colored as an option of multiple option (secondary toolbar) or maybe you might have a better idea.

By the way about the arrowhead, is it possible to modify it proportionally to its width?
Here's an example video (I wanted to post this video on #75, but now that I'm typing about arrows I think it's a good opportunity to show it to you hehe)
https://user-images.githubusercontent.com/20199672/120061740-34ac6100-c024-11eb-9433-4329ef946f33.mp4
Maybe it could solve that problem that when we increase the width of the pen, the arrowhead loses its shape.

Well. that's all as far as I can tell you.

I apologize if my post is quite long but I wanted to express what I found in my tests (results) because I want to contribute to the improvement of ppink.

Thanks in advance!

**Comment by pubpub-zz** [comment]
>From NovaInc 
> 
> These are the tests for version 2.
> 
> When I had smooth on and I went to take the screenshot, after finishing drawing the snapshot box the edit text window popped up and I immediately got an error after that, then it crashed. With smooth off I had the same unintended stroke bug appear again when trying to draw the snapshot box from the top left corner.

a crash.txt file should have been generated. can you send it ?

> 
> I also noticed that when drawing slower with smooth curves on, there are more glitches. In this example I tried to do lines 1 and 3 quickly with pen and mouse respectively, then lines 2 and 4 are made slowly using the same input methods.

I would guess the number of vertex was higher and Windows has more trouble to draw a nice line. My is just using windows GDI.
no idea of what I could about.

> This is not related to the stroke styles, but I think also having pens in the toolbar in 1-2-3-4-5 on the first line and then 6-7-8-9-10 on the second line would be more intuitive than 1-3-5-7-9, 2-4-6-8-10, since that's the way we read. Top left to top right then skip to the next line.

I Like your idea I will modify default hotkeys.ini 😀

**Comment by NOVAinc** [comment]
No problem! I don't think most people will do slow strokes so hopefully it won't be an issue. As for the crash file, here it is!

[crash.txt](https://github.com/pubpub-zz/ppInk/files/6565385/crash.txt)

**Comment by pubpub-zz** [comment]
> 
> 
> No problem! I don't think most people will do slow strokes so hopefully it won't be an issue. As for the crash file, here it is!
> 
> [crash.txt](https://github.com/pubpub-zz/ppInk/files/6565385/crash.txt)

Thanks. 
I can not come to any conclusion: the crask just reports the log report from the dialog box. (due to Event processing)  I have not traces why the dialog box opened. Deeper code review required 😑

**Comment by pubpub-zz** [comment]
From chrisj0192 (https://github.com/pubpub-zz/ppInk/issues/98#issuecomment-850757861)
> I was trying to combine "line" with "dashed line" and was trying to find an easy way to do it dynamically by setting "alt + d" for the dashed lines. But the dashed line doesn't reset when I release "alt" key.

Agree with your idea, not sure how to code that yet. Will put that in the stack.

> Another one that I've noticed is that when I deactivate ppink and activate it again, dashed lines don't start with the principal solid line.

For me : you can edit pens and closing/reopening toolbar they are back. Once modified throught hotkeys, you can see mods in option dialogs. Once saved they are restored at next startup : can you confirm behavior on your side ?

> I think the principal line (green) is the most useful in this case. and the other types of lines could be secondary lines.
> 
> A short example what I would like to do with less effort.
> https://user-images.githubusercontent.com/20199672/120055616-df108e00-bffc-11eb-80fc-82f9eb39e678.mp4

Alt+D pushed in the work stack .
> 
> Testing dashed lines with "the smooth curve option" disabled.
> https://user-images.githubusercontent.com/20199672/120055646-05362e00-bffd-11eb-8abc-7c22bb69ade9.mp4

About Arrow Head not so nice drawing, I rely on windows GDI+  :  nothing to be done...

> 
> Testing other shapes and the hightlighter with dashed lines.
> 
>     * In this case I've noticed that when I made strokes with the hightlighter there are some weird lines and some irregularities in its linear shape.
>       https://user-images.githubusercontent.com/20199672/120055667-21d26600-bffd-11eb-8b19-c1b1bc2108bb.mp4
> 
> 
> That's all I can tell you. I don't know if you might want to consider what I told you above to make this process more dynamic. I'd love to do a great change lines with dashed lines in a fast way with "alt" key.
> 
> For me it is enough if I can make a dashed arrow or a dashed line with an option similar to lines, arrows, rectangles and ovals regardless of the strokes because I know that strokes are more difficult.

This affecting Pens, it can not be viewed as a tool. Will work on alt for temporary should be enough

One point I've noticed and fixed from your video : in-progress drawing does not show LineStyle

**Comment by pubpub-zz** [comment]
> VIDEO MESSAGE CORRECTION about the arrowhead: "I don't know If there is a way that the arrowhead is proportional to the width of its line. I was trying to modify the option values that are available in the option menu (arrowhead: aperture / length) but I couldn't get a proportional arrowhead with its length)"
> This is the video about the arrowhead:
> https://user-images.githubusercontent.com/20199672/120061740-34ac6100-c024-11eb-9433-4329ef946f33.mp4
> Maybe it could solve that problem that when we increase the width of the pen, the arrowhead loses its shape.
> 

Not sure how to code that without major impact. Will think about

**Comment by pubpub-zz** [comment]
I close this issue. Reopen it of send me a comment(even if closed about if required
